version: '2'
services:
  db:
    image: 'mysql:5.7'
    container_name: 'mysql-test'
    volumes:
      - '~/dev/dbs-data/mysql:/var/lib/mysql'
    restart: 'always'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'order'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-time-zone=+09:00"]